# basic imports
defaults:
  - discriminator: ???
  - selection
  - _self_

# mflow run info
path_to_mlflow: ???
experiment_id: ???
run_id: ???

# phase space region
vs_type: ??? # jet/e/mu
dataset_alias: ??? # alias to reference a mixture of input_samples below, e.g. tau_DY_jet_TT
pt_bins: [[20, 100], [100, 1000],]
eta_bins: [[0, 2.3], [2.3, 2.5]]
dm_bins: [[0, 1, 2, 10, 11]]

# selection
input_branches: [ 'tau_pt', 'tau_eta', 'tau_decayMode' , 'tau_dz',  'tau_byDeepTau2018v2p5VSmuraw', 'tau_byDeepTau2018v2p5VSjetraw'] # add here WP branches if necessary 
cuts: "(${apply_dm_cuts}) and (abs(tau_dz) < 0.2)" 
WPs_to_require: null # null to not apply WP as selection
# WPs_to_require: ### example for vs. jet
#   jet : Tight

# inputs/paths
input_samples: # "sample_alias": [list of strings with tau types to be selected]
  WToTauNu_M-20_v3: ['tau']
  DYJetsToLL_M-50-madgraphMLM_v3: ['e']
path_to_input: null
path_to_pred: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_target: '${path_to_mlflow}/${experiment_id}/${run_id}/artifacts/predictions/{sample_alias}/*_pred.h5'
path_to_weights_taus: null
path_to_weights_vs_type: null

# misc.
roc_prune_decimal: # precision on TPR rounding 
  e: 3
  mu: 4
  jet: 3
